# for REST CLIENT extension
@url=http://localhost:3010

GET {{url}}/api/users
###
GET {{url}}/api/users?filter=name&value=Qas2
###
GET {{url}}/api/users/1
###
POST {{url}}/api/users/ HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

{
  "username": "qas4", 
  "displayName": "Qasi4"
}
###
PUT {{url}}/api/users/1 HTTP/1.1
Content-Type: application/json

{
  "username": "Qas4", 
  "displayName": "Qasi4"
}
###
PATCH {{url}}/api/users/1 HTTP/1.1
Content-Type: application/json

{
  "username": "Qas4"
}
###
DELETE {{url}}/api/users/2 HTTP/1.1
###
GET {{url}}/api/products
###
GET {{url}}/api/products/2
###
PUT {{url}}/api/empoloyees/
###

GET {{url}}/
###
POST {{url}}/api/auth/ HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json
rest-client.rememberCookiesForSubsequentRequests

{
  "username": "qas4", 
  "password": "hello123"
}
###

GET {{url}}/api/auth/status
###
POST {{url}}/api/cart
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

{
  "name": "Orange", 
  "price": 1.99
}
###
POST {{url}}/api/cart
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

{
  "name": "Carrots", 
  "price": 2.99
}
###

GET {{url}}/api/cart
###

# pasport
POST {{url}}/api/authwithpassport/ HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json
rest-client.rememberCookiesForSubsequentRequests

{
  "username": "qas4", 
  # "email": "qas4@gmail.com", 
  "password": "hello123"
}
###

GET {{url}}/api/authwithpassport/status
###

POST {{url}}/api/authwithpassport/logout
###
